name: Build and Release

on:
  push:
    tags:
      - "v*" # Спрацює тільки коли ти пушиш тег, що починається з "v" (наприклад, v1.0.1)

jobs:
  build-and-release:
    name: Build and Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🛠️ Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: 🚀 Publish Windows x64 (Single File)
        run: dotnet publish EntropyTunnel.Client/EntropyTunnel.Client.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o ./publish/win-x64

      - name: 📦 Create GitHub Release and Upload .exe
        uses: softprops/action-gh-release@v2
        with:
          files: ./publish/win-x64/EntropyTunnel.Client.exe
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
