// <auto-generated />
using System;
using EntropyTunnel.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EntropyTunnel.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260527194539_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EntropyTunnel.Server.Data.AccountRow", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("text")
                        .HasColumnName("account_id");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.HasKey("AccountId")
                        .HasName("pk_accounts");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("EntropyTunnel.Server.Data.AgentRow", b =>
                {
                    b.Property<string>("ClientId")
                        .HasColumnType("text")
                        .HasColumnName("client_id");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_id");

                    b.HasKey("ClientId")
                        .HasName("pk_agents");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_agents_account_id");

                    b.ToTable("agents", (string)null);
                });

            modelBuilder.Entity("EntropyTunnel.Server.Data.ChaosRuleRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_id");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data");

                    b.HasKey("Id")
                        .HasName("pk_chaos_rules");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_chaos_rules_client_id");

                    b.ToTable("chaos_rules", (string)null);
                });

            modelBuilder.Entity("EntropyTunnel.Server.Data.LogRow", b =>
                {
                    b.Property<Guid>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_id");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("RequestId")
                        .HasName("pk_request_log");

                    b.HasIndex("ClientId", "Timestamp")
                        .HasDatabaseName("ix_request_log_client_id_timestamp");

                    b.ToTable("request_log", (string)null);
                });

            modelBuilder.Entity("EntropyTunnel.Server.Data.MockRuleRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_id");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data");

                    b.HasKey("Id")
                        .HasName("pk_mock_rules");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_mock_rules_client_id");

                    b.ToTable("mock_rules", (string)null);
                });

            modelBuilder.Entity("EntropyTunnel.Server.Data.RoutingRuleRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_id");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data");

                    b.HasKey("Id")
                        .HasName("pk_routing_rules");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_routing_rules_client_id");

                    b.ToTable("routing_rules", (string)null);
                });

            modelBuilder.Entity("EntropyTunnel.Server.Data.AgentRow", b =>
                {
                    b.HasOne("EntropyTunnel.Server.Data.AccountRow", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agents_accounts_account_id");
                });

            modelBuilder.Entity("EntropyTunnel.Server.Data.ChaosRuleRow", b =>
                {
                    b.HasOne("EntropyTunnel.Server.Data.AgentRow", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chaos_rules_agents_client_id");
                });

            modelBuilder.Entity("EntropyTunnel.Server.Data.LogRow", b =>
                {
                    b.HasOne("EntropyTunnel.Server.Data.AgentRow", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_request_log_agents_client_id");
                });

            modelBuilder.Entity("EntropyTunnel.Server.Data.MockRuleRow", b =>
                {
                    b.HasOne("EntropyTunnel.Server.Data.AgentRow", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mock_rules_agents_client_id");
                });

            modelBuilder.Entity("EntropyTunnel.Server.Data.RoutingRuleRow", b =>
                {
                    b.HasOne("EntropyTunnel.Server.Data.AgentRow", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_routing_rules_agents_client_id");
                });
#pragma warning restore 612, 618
        }
    }
}
